language: php
dist: trusty
sudo: false

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly

addons:
    apt:
        packages:
        - libtomcrypt-dev

notifications:
    email: false
    irc:
      channels:
        - "irc.iiens.net#Clicky"
      on_success: change
      on_failure: always

before_script:
    - wget https://github.com/fpoirotte/tomcrypt/archive/master.tar.gz
    - tar xavf master.tar.gz
    - pear install tomcrypt-master/package.xml
    - rm -rf vendor/
    - rm composer.lock
    - composer self-update -n
    - composer install -n

script:
    - vendor/bin/phpunit --coverage-clover clover.xml
    - vendor/bin/phpcs

after_success:
    - composer require --dev satooshi/php-coveralls
    - travis_retry vendor/bin/php-coveralls -n -v
